In [ ]:
!pip install ntscraper

Collecting ntscraper
  Downloading ntscraper-0.3.17-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: requests>=2.28 in /usr/local/lib/python3.11/dist-packages (from ntscraper) (2.32.3)
Requirement already satisfied: beautifulsoup4>=4.11 in /usr/local/lib/python3.11/dist-packages (from ntscraper) (4.13.3)
Requirement already satisfied: lxml>=4.9 in /usr/local/lib/python3.11/dist-packages (from ntscraper) (5.3.1)
Requirement already satisfied: tqdm>=4.66 in /usr/local/lib/python3.11/dist-packages (from ntscraper) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11->ntscraper) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11->ntscraper) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28->ntscraper) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28->ntscraper) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28->ntscraper) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28->ntscraper) (2025.1.31)
Downloading ntscraper-0.3.17-py3-none-any.whl (12 kB)
Installing collected packages: ntscraper
Successfully installed ntscraper-0.3.17

In [ ]:
from ntscraper import Nitter

In [ ]:
scraper = Nitter(0)

Testing instances: 100%|██████████| 6/6 [00:11<00:00,  1.86s/it]

In [ ]:
import random

# Manually provide a list of Nitter instances.
instances = [
    "https://nitter.net",
    "https://nitter.42l.fr",
    "https://nitter.pussthecat.org",
    "https://nitter.nixnet.services",
    "https://nitter.kavin.rocks",
    # Add more instances as needed
]

# Initialize Nitter with a specific instance or a list.
# Option 1: Select a random instance from the list.
instance = random.choice(instances)
scraper = Nitter(instance=instance)

# Option 2: Provide the entire list to Nitter.
# scraper = Nitter(instances=instances)

# Now, try fetching tweets.
tweets = scraper.get_tweets("india", mode='hashtag', number=10)

TypeError: Nitter.__init__() got an unexpected keyword argument 'instance'

In [ ]:
final_tweets = []
for x in tweets['tweets']:
    data = [x['link'], x['text'],x['date'],x['stats']['likes'],x['stats']['comments']]
    final_tweets.append(data)

In [ ]:
dat = pd.DataFrame(final_tweets, columns =['twitter_link','text','date','likes','comments'])

NameError: name 'pd' is not defined

In [ ]:
dat

,twitter_link,text,date,likes,comments
0,https://twitter.com/Muhamma5615510/status/1723...,Just remember 2 six to ashwin just remember 4 ...,"Nov 13, 2023 · 7:20 AM UTC",0,0
1,https://twitter.com/bluestone_leo/status/17239...,And the next day they said - “YOU ALL ARE FIRE...,"Nov 13, 2023 · 7:20 AM UTC",0,0
2,https://twitter.com/Wants_to_know__/status/172...,Because it was made from your mother's 🍊🍊 milk 🤱,"Nov 13, 2023 · 7:20 AM UTC",0,0
3,https://twitter.com/total_woke_/status/1723209...,"Dear Friends from Pakistan, This Tweet doesn't...","Nov 11, 2023 · 5:21 AM UTC",3709,55
4,https://twitter.com/asmgn/status/1723963919142...,When bowling was more fantastic. 😂🤣😜,"Nov 13, 2023 · 7:20 AM UTC",0,0
5,https://twitter.com/Raja69313293/status/172396...,"Ek Tha EX50,55,73 😂😂 😂","Nov 13, 2023 · 7:19 AM UTC",0,0
6,https://twitter.com/bsindia/status/17239638212...,"Virender Sehwag, Aravinda de Silva, and Diana ...","Nov 13, 2023 · 7:19 AM UTC",0,0
7,https://twitter.com/Sportskeeda/status/1723937...,Three new inductees in ICC Hall of Fame 🤩 #Cr...,"Nov 13, 2023 · 5:35 AM UTC",285,3
8,https://twitter.com/ManeeshSol84/status/172396...,Induction into ICC Hall of fame 🥳 @virenderseh...,"Nov 13, 2023 · 7:19 AM UTC",0,0
9,https://twitter.com/KhiltaChaman/status/172396...,Dashing - Bowler Bashing Batsman @v...,"Nov 13, 2023 · 7:18 AM UTC",0,0

In [ ]:
tweets = scraper.get_profile_info("JeffBezos")

13-Nov-23 12:46:47 - No instance specified, using random instance https://nitter.soopy.moe

In [ ]:
tweets

{'image': 'https://pbs.twimg.com/profile_images/1591558315254890500/ETIHb4Nl_400x400.jpg',
 'name': 'Jeff Bezos',
 'username': '@JeffBezos',
 'id': '15506669',
 'bio': 'Amazon. Blue Origin. Washington Post. Bezos Earth Fund. Bezos Academy.',
 'location': '',
 'website': 'https://hoo.be/jeffbezos',
 'joined': '10:38 PM - 20 Jul 2008',
 'stats': {'tweets': 397,
  'following': 276,
  'followers': 6294608,
  'likes': 131,
  'media': 171}}

In [ ]:
tweets['image']

'https://pbs.twimg.com/profile_images/1591558315254890500/ETIHb4Nl_400x400.jpg'

In [ ]:
def get_tweets(name, modes, no):
    tweets = scraper.get_tweets(name, mode = modes, number=no)
    final_tweets = []
    for x in tweets['tweets']:
        data = [x['link'], x['text'],x['date'],x['stats']['likes'],x['stats']['comments']]
        final_tweets.append(data)
    dat= pd.DataFrame(final_tweets, columns =['twitter_link','text','date','likes','comments'])
    return dat

In [ ]:
data = get_tweets('JeffBezos','user',6)

In [ ]:
data

,twitter_link,text,date,likes,comments
0,https://twitter.com/SenBillNelson/status/17179...,Impressive visit to the @blueorigin Huntsville...,"Oct 27, 2023 · 2:00 PM UTC",2290,568
1,https://twitter.com/torybruno/status/166661245...,Nominal run!,"Jun 8, 2023 · 1:05 AM UTC",3645,881
2,https://twitter.com/JeffBezos/status/165957630...,Honored to be on this journey with @NASA to la...,"May 19, 2023 · 3:06 PM UTC",12285,3728
3,https://twitter.com/JeffBezos/status/162522482...,Big milestone. Kudos and congrats to the whole...,"Feb 13, 2023 · 8:06 PM UTC",4886,3777
4,https://twitter.com/JeffBezos/status/162046673...,Episode 3 of Last of Us is unbelievably good s...,"Jan 31, 2023 · 4:59 PM UTC",30056,2526
5,https://twitter.com/JeffBezos/status/161941882...,Thank you Bill and Tim. So nice. Gratitude.,"Jan 28, 2023 · 7:35 PM UTC",2833,1097

In [ ]:
scraper.get_profile_info('BillGates')

{'image': 'https://pbs.twimg.com/profile_images/1674815862879178752/nTGMV1Eo_400x400.jpg',
 'name': 'Bill Gates',
 'username': '@BillGates',
 'id': '50393960',
 'bio': "Sharing things I'm learning through my foundation work and other interests.",
 'location': 'Seattle, WA',
 'website': 'https://gatesnot.es/blog',
 'joined': '6:44 PM - 24 Jun 2009',
 'stats': {'tweets': 4440,
  'following': 583,
  'followers': 64283753,
  'likes': 540,
  'media': 1511}}